name: causalimpact
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel=5.3.0
  - ipython=7.16.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jupyter=1.0.0
  - jupyter_client=6.1.3
  - jupyter_console=6.1.0
  - jupyter_core=4.6.3
  - jupyterlab=2.1.5
  - jupyterlab_server=1.1.5
  - matplotlib=3.2.2=0
  - matplotlib-base=3.2.2
  - notebook=6.0.3
  - numpy=1.18.5
  - numpy-base=1.18.5
  - pandas=1.0.5
  - pip=20.1.1
  - python=3.7.7
  - python-dateutil=2.8.1
  - pyyaml=5.3.1
  - scikit-learn=0.23.1
  - scipy=1.5.0
  - yaml=0.2.5
  - statsmodels=0.13.2
  - seaborn=0.11.2

  - pip:
      - pycausalimpact=0.1.1

